# Generated by Django 4.0.3 on 2022-03-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_rename_price_books_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='amount',
            new_name='price',
        ),
    ]
